version: '3'
services:
  db:
    image: postgres:11.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobs_dev
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        - NODE_ENV=$NODE_ENV
        - DATABASE_PORT=5432
        - DATABASE_HOST=db
        - DATABASE_URL=postgres://postgres@db/jobs_dev
    volumes:
      - .:/home/jobs-backend/
      - /home/jobs-backend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    restart: always
