# docker-compose.yml
version: '3'
services:
  db_dev:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobs_dev
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobs

  web:
    build: .
    volumes:
      - .:/jobs-backend
    ports:
      - '3000:3000'
    depends_on:
      - db_dev
    links:
      - db_dev
    environment:
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=postgres://postgres@db_dev
