# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/jobs-backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db/
