import { GeoPoint, Timestamp } from '@google-cloud/firestore'
import { Job } from '../src/types'

// tslint:disable:max-line-length

export const seedJobs: Job[] = [
  {
    title: 'Frontend developer',
    homeOffice: 2,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    teaser: 'Build the next-gen health platform. Things and stuff and more things.',
    company: 'Magmina',
    coords: new GeoPoint(47.3916487, 8.5045223),
    logo: 'https://via.placeholder.com/60x60',
    location: 'Snowville, Zurich',
    contract_duration: null,
    contract_type: 'part-time',
    contract_percentage: 80,
    salary: [100, 130],
    equity: [0.1, 0.4],
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    category: 'frontend',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Fullstack developer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: "Body scanning with crazy algorithms. It's so cool. Join us.",
    company: 'Valreda, Geneva',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Cassel',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [80],
    equity: [0.05, 0.1],
    category: 'fullstack',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'UX Consultant',
    homeOffice: 0,
    isRemote: true,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: "Build the next bitcoin. It's going to be amazing.",
    company: 'Parleynet',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Chaparrito',
    contract_duration: 6,
    contract_type: 'contractor',
    contract_percentage: 100,
    salary: [600, 700],
    equity: null,
    category: 'designer-ux',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Junior designer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    coords: new GeoPoint(47.3916487, 8.5045223),
    email: 'robinsonnieves@endicil.com',
    teaser: 'Build the next-gen health platform',
    company: 'Velity',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Chicopee',
    contract_duration: null,
    contract_type: 'part-time',
    contract_percentage: 80,
    salary: [75, 90],
    equity: null,
    category: 'designer-ux',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Project Manager',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Songlines',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Rosburg',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [145],
    equity: [3],
    category: 'business-product',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Devops Dude',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Zorromop',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Sunriver',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [60],
    equity: [0],
    category: 'devops-sysadmin',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'CTO',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Zilla',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Hailesboro',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: null,
    equity: [9],
    category: 'business-product',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Backend developer',
    homeOffice: 0,
    isRemote: true,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Utara',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Allensworth',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [90],
    category: 'backend',
    equity: [7],
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'React Developer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Quonata',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Dundee',
    contract_duration: null,
    contract_type: 'internship',
    contract_percentage: 100,
    salary: [60],
    category: 'frontend',
    equity: null,
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Marketing Manager',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Keengen',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Outlook',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [120, 150],
    equity: [5],
    category: 'sales-marketing',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Customer Support Rep',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Podunk',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Ruckersville',
    contract_duration: 12,
    contract_type: 'internship',
    contract_percentage: 100,
    salary: [50, 60],
    equity: [5],
    category: 'customer-support',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'CBO - Chief Banana Officer',
    homeOffice: 0,
    isRemote: true,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Terascape',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Yettem',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [75],
    equity: null,
    category: 'business-product',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'CTO',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Realysis',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Loveland',
    contract_duration: null,
    contract_type: 'part-time',
    contract_percentage: 70,
    salary: [180, 200],
    equity: [14],
    category: 'business-product',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Frontend developer',
    homeOffice: 1,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Imageflow',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Morningside',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [75],
    equity: null,
    category: 'frontend',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Fullstack developer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Greeker',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Staples',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [85, 105],
    equity: null,
    category: 'fullstack',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'SRE - Site Reliability Engineer',
    homeOffice: 3,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Oulu',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Nogal',
    contract_duration: 24,
    contract_type: 'part-time',
    contract_percentage: 50,
    salary: null,
    equity: null,
    category: 'devops-sysadmin',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Europe Sales Manager',
    homeOffice: 2,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Caxt',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Healy',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [50, 65],
    equity: [1, 2],
    category: 'sales-marketing',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Backend developer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Zytrac',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Wakarusa',
    contract_duration: 9,
    contract_type: 'contractor',
    contract_percentage: 100,
    salary: [700, 1000],
    equity: null,
    category: 'backend',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Technical Co-founder',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Cujo',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Warren',
    contract_duration: null,
    contract_type: 'part-time',
    contract_percentage: 80,
    salary: [100],
    equity: [5],
    category: 'frontend',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  },
  {
    title: 'Angular Developer',
    homeOffice: 0,
    isRemote: false,
    created_at: Timestamp.fromDate(new Date()),
    link: 'https://apple.com/jobs',
    email: 'robinsonnieves@endicil.com',
    coords: new GeoPoint(47.3916487, 8.5045223),
    teaser: 'Build the next-gen health platform',
    company: 'Pulze',
    logo: 'https://via.placeholder.com/60x60',
    location: 'Norris',
    contract_duration: null,
    contract_type: 'full-time',
    contract_percentage: 100,
    salary: [10, 15],
    equity: null,
    category: 'frontend',
    description:
      "<div><p>Buying a home is one of life’s biggest financial and emotional decisions. We’re here to make it less stressful, more predictable, and more organized. We’ve built Folio: the first AI powered operating system for real estate transactions. Folio automatically organizes key transaction details and data to take the stress out of the process for both real estate agents and their clients.</p><p>The magic happens right in an agent’s email, putting all the key details about a transaction right at their fingertips -- while organizing each transaction into Smart Folders and a timeline that clients use to stay on track.</p><p>We are a team of passionate product people and engineers that gets excited about solving complex processes and creating value for our users with AI and machine learning. We’re currently looking for full-stack engineers, data scientists and machine learning experts to add to our remote team.</p><p>We are a strong agile shop - we practice solo and pair programming, TDD, daily standups, weekly IPMs and weekly retros. Our product development process is driven by user research in which all members of the team are involved. </p><p>As a full-stack engineer at Amitree, you’ll have the opportunity to work on all aspects of the product, from our machine-learning algorithms that analyze millions of emails each day all the way through our front-end interfaces. You'll work to write well tested code and ship it to production in a matter of hours. The company places a high value on the health of the codebase, and allots time every week to the engineering team to do maintenance tasks that help keep our system up-to-date and healthy. Technical qualifications are listed below.</p><p><strong>Requirements</strong>:</p><ul><li>Extensive senior-level software development experience, managing and scaling complex web applications, algorithm design, handling and mitigating production incidents, and software architecture and design</li><li>Significant experience with a Javascript front-end framework</li><li>Experience with automated testing</li></ul><p><strong>Nice-to-haves</strong>:</p><ul><li>BA degree, preferably in computer science</li><li>Experience with Ruby on Rails</li><li>Experience with test-driven development</li><li>Experience with pair programming</li><li>Experience with continuous deployment, continuous integration, and testing frameworks</li></ul><p><strong>Perks</strong>:</p><ul><li>Autonomy and responsibility, control and ownership over what you produce</li><li>Health, dental, and vision insurance with fully paid premium for you and your dependents</li><li>Reimbursement for the cost of a gym &amp; One Medical membership</li><li>Flexible paid time off / vacation - we encourage everyone to take at least three weeks off each year</li><li>401(k) plan administered by Vanguard's website</p></li></ul></div>"
  }
]
